# Criação com container do banco

# Usa a imagem oficial do MySQL 8
FROM mysql:8.0

WORKDIR /bancodados

USER mysql

# Define variáveis de ambiente para o MySQL, correspondendo ao seu application.properties

# Define o nome do banco de dados que será criado automaticamente na inicialização
ENV MYSQL_DATABASE=mydb

# Define o usuário 
ENV MYSQL_USER=rm554556

# Define a senha 
ENV MYSQL_PASSWORD=181085

# Define a senha do usuário root do MySQL 
ENV MYSQL_ROOT_PASSWORD=pass_devforge

# Expõe a porta padrão do MySQL
EXPOSE 3306

# Comando padrão para iniciar o MySQL 
CMD ["mysqld"]