spring.application.name=AbrigoSmart

#Banco de Dados da Orcle FIAP
#spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl
#spring.datasource.username=rm554556
#spring.datasource.password=181085
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


#Banco de Dados MySQL


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
spring.datasource.username=rm554556
spring.datasource.password=181085

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect











# Cache
spring.cache.type=simple