spring.application.name=AbrigoSmart

#Banco de Dados da Orcle FIAP
#spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl
#spring.datasource.username=rm554556
#spring.datasource.password=181085

# Para uso Devops

spring.datasource.url=jdbc:oracle:thin:@oracle-xe:1521/ORCLGS
spring.datasource.username=system
spring.datasource.password=abrigosmart2025


spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect




